### ISSUE TITLE
Unable to install new node versions

### ISSUE THREAD

**Issue by makenosound** [icelab/babushka-deps#12]
I needed to install node 4.x series today and I couldn’t manage to get the default `nodenv` install to update to list the new versions. The recommendation now appears to be to install `node-build` alongside for this version information, but installing it and updating the existing `nodenv` didn’t help me.

Instead I had to remove the existing `nodenv` build:

```bash
rm -rf `nodenv root`
```

And then I installed it through brew alongside `node-build`:

```bash
brew install nodenv node-build
```

And now I have all the latest `node-build` versions available to install.

**Comment by chrisbuttery** [comment]
@makenosound You should be able to `cd` into `~/.nodenv/plugins/node-build` and `git pull`.
This will bring the latest versions in, which you can then list with `nodenv install -l`

**Comment by makenosound** [comment]
@chrisbuttery Ta, I had forgotten that distinction because it’s (stupidly) hidden and not really mentioned in the docs.
